apiVersion: v1
kind: Pod
metadata:
  name: violation-pod
  labels:
    app: violation-pod
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: operator/demo-profile/violation.json
  containers:
  - name: echo-server
    image: mauilion/echo-server:stable
    securityContext:
      allowPrivilegeEscalation: false
