apiVersion: v1
kind: Pod
metadata:
  name: run-pod
  labels:
    app: run-pod
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  containers:
  - name: echo-server
    image: mauilion/amicontained-pause:stable
    securityContext:
      allowPrivilegeEscalation: false
